### ISSUE TITLE
granular overlay options for backend tasks

### ISSUE THREAD

**Issue by ophian** [s9y/Serendipity#234]
References #222  (A little love for tags in the entry editor)

>> Couldn't we make this granular for tags?

> I already suggested to make that config option more granular in the forums because I think people should be able to i.e. use overlays in the media db, but not for tags/categories if they so desire.
> 
> However, I don't think that's necessary for RC, and it definitely is not related to this issue.

-- 

>> It is not possible to solve this through a simpletags-plugin-setting?​

> An option in the freetags plugin, eg 'Use overlay: yes no' and then check this in ... whereever it is done.

I would opt to have this granular option somewhere. (At least and in special for tags!)

**Comment by garvinhicking** [comment]
Changed milestone to future, I think we should not delay the 2.0 release due to this, since it's quite a lot of work and would require another RC due to the deeper changes.

**Comment by garvinhicking** [comment]
Please check out commit 5f7f2e5 where I implemented this with a simple stringlist we can in the future expand with more tags. It's a bit dirty to use a string there, but we have no other means to implement a list of multiple selections. I didn't want to have one radio-button for each area, that would be bloated.

**Comment by yellowled** [comment]
Just tested it. Good enough for me. (Meaning I don't think it needs to be a more comfortable interface, either.)

Watch how no one with actually use this, though. ;-)

Close?

**Comment by ophian** [comment]
I tried it, entering `categories, tags` for example. I first thought it to be not working, then I discovered the "toolbar" like top buttons have to be clicked 2 times to jump to the fields and the inner-form jump for shown categories and tags to be disabled at all. I think that needs improvement to be more intuitive.

Another thing I still have in mind and could not test it...: For new installations entryproperties is now by default enabled. Updating an existing blog installation which hasn't had installed it before, will still not have it. Do we rely on its usage somehere?

**Comment by garvinhicking** [comment]
Please  create seperate issues or threads on the forums for things like these. It's really not good to mix up issues. (Answer: We don't require entryproperties)

Also it would be good to create a seperate issue for changing the behaviour of "non-popup" categories/tags buttons, this issue here is only about the granular control option not the functionality of popups themselves.

Thanks :)

**Comment by ophian** [comment]
For me it was related... since I tried out the new granular option, entering `categories, tags` for example. A new issue was opened for this. But now I opened the ML, clicked on a preview image, which should open in the overlay, but opens in a popup. So there is still an issue, sorry!

**Comment by yellowled** [comment]
> But now I opened the ML, clicked on a preview image, which should open in the overlay, but opens in a popup.

I just now tested this in FF with categories and tags disabled in Personal Settings. It opens the image in an overlay. Does your test blog maybe have the previous option “Popups für das Backend verwenden?” set to “Yes”?

**Comment by ophian** [comment]
I don't know why I had this in both blogs, but "Yes". That was the issue, without granular is working. Thanks.
